-- Table Sessions: Track active table usage for QR ordering
-- When a customer scans QR and starts ordering, a session is created
-- Staff releases the table after payment is done

CREATE TABLE IF NOT EXISTS public.table_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_number INTEGER NOT NULL CHECK (table_number >= 1 AND table_number <= 18),
  session_token TEXT NOT NULL UNIQUE,
  customer_name TEXT,
  party_size INTEGER DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'ordering', 'bill_requested', 'paid', 'released')),
  total_amount INTEGER DEFAULT 0,
  orders JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  released_at TIMESTAMP WITH TIME ZONE,
  released_by TEXT -- Staff member name
);

-- Only one active session per table at a time
CREATE UNIQUE INDEX IF NOT EXISTS idx_table_sessions_active_table
  ON public.table_sessions(table_number)
  WHERE status IN ('active', 'ordering', 'bill_requested');

-- Indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_table_sessions_status ON public.table_sessions(status);
CREATE INDEX IF NOT EXISTS idx_table_sessions_token ON public.table_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_table_sessions_table_number ON public.table_sessions(table_number);

-- Enable Row Level Security
ALTER TABLE public.table_sessions ENABLE ROW LEVEL SECURITY;

-- Policies
-- Anyone can create a session (via QR scan)
CREATE POLICY "Anyone can create table sessions"
  ON public.table_sessions
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- Anyone can read sessions (to check table availability)
CREATE POLICY "Anyone can read table sessions"
  ON public.table_sessions
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- Anyone can update sessions (for adding orders)
CREATE POLICY "Anyone can update table sessions"
  ON public.table_sessions
  FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- Trigger to update updated_at
CREATE TRIGGER update_table_sessions_updated_at
  BEFORE UPDATE ON public.table_sessions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Grant permissions
GRANT ALL ON public.table_sessions TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.table_sessions TO anon;

-- QR Tokens: Store the unique tokens for each table's QR code
-- These are generated by staff and printed on QR codes
CREATE TABLE IF NOT EXISTS public.table_qr_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_number INTEGER NOT NULL UNIQUE CHECK (table_number >= 1 AND table_number <= 18),
  token TEXT NOT NULL UNIQUE,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.table_qr_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read QR tokens"
  ON public.table_qr_tokens
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Authenticated can manage QR tokens"
  ON public.table_qr_tokens
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT ON public.table_qr_tokens TO anon;
GRANT ALL ON public.table_qr_tokens TO authenticated;

-- Insert default tokens for all 18 tables
INSERT INTO public.table_qr_tokens (table_number, token) VALUES
  (1, 'TCH-T01-A7X9'),
  (2, 'TCH-T02-B3K2'),
  (3, 'TCH-T03-C8M5'),
  (4, 'TCH-T04-D2N7'),
  (5, 'TCH-T05-E6P1'),
  (6, 'TCH-T06-F9Q4'),
  (7, 'TCH-T07-G1R8'),
  (8, 'TCH-T08-H5S3'),
  (9, 'TCH-T09-J7T6'),
  (10, 'TCH-T10-K4U9'),
  (11, 'TCH-T11-L2V5'),
  (12, 'TCH-T12-M8W1'),
  (13, 'TCH-T13-N3X7'),
  (14, 'TCH-T14-P6Y2'),
  (15, 'TCH-T15-Q9Z4'),
  (16, 'TCH-T16-R1A8'),
  (17, 'TCH-T17-S5B3'),
  (18, 'TCH-T18-T7C6')
ON CONFLICT (table_number) DO NOTHING;

COMMENT ON TABLE public.table_sessions IS 'Active table sessions for QR ordering - tracks who is using which table';
COMMENT ON TABLE public.table_qr_tokens IS 'Unique tokens for each table QR code - required to access table ordering';
